name: "YOLO11_OBB_PRE"
platform: "tensorrt_plan"
max_batch_size: 16
default_model_filename: "model.plan"

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [20, 8400]
  }
]

instance_group [
  { count: 1, kind: KIND_GPU, gpus: [0] }
]
