name: "RFDETR_DET_PRE"
platform: "tensorrt_plan"
max_batch_size: 16
default_model_filename: "model.plan"

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 512, 512]
  }
]

output [
  {
    name: "dets"
    data_type: TYPE_FP32
    # [batch, 300, 4] 归一化 cxcywh
    dims: [300, 4]
  },
  {
    name: "labels"
    data_type: TYPE_FP32
    # [batch, 300, 91] logits（最后一维为背景）
    dims: [300, 91]
  }
]

instance_group [
  { count: 1, kind: KIND_GPU, gpus: [0] }
]
