name: "CUSTOM_LABELS"
backend: "python"
max_batch_size: 0

input [
  {
    name: "model_name"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "labels"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

parameters: {
  key: "names_directory"
  value: { string_value: "/models/CUSTOM_LABELS/names" }
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
