name: "CLASSIFIER_SMOKING_POSTPROCESS"
backend: "classifier_postprocess"
max_batch_size: 16

input [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [2]
  }
]

output [
  {
    name: "classes"
    data_type: TYPE_INT32
    dims: [2]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [2]
  }
]

parameters: {
  key: "num_classes"
  value: { string_value: "2" }
}
parameters: {
  key: "top_k"
  value: { string_value: "2" }
}
parameters: {
  key: "apply_softmax"
  value: { string_value: "true" }
}
parameters: {
  key: "max_batch_size"
  value: { string_value: "16" }
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]
